---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_iterm: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
- TV
- Podcasts
- 'App Store'
- Music
- Keynote
- Numbers
- Pages
- Maps
- Reminders
dockitems_persist:
- name: "Launchpad"
  pos: 1
- name: "Safari"
  pos: 2
- name: "Mail"
  pos: 3
- name: "Contacts"
  pos: 4
- name: "Calendar"
  pos: 5
- name: "Notes"
  pos: 6
- name: "iTerm"
  path: "/Applications/iTerm.app"
  pos: 7
- name: "WhatsApp"
  path: "/Applications/WhatsApp.app"
  pos: 9
- name: "Spotify"
  path: "/Applications/Spotify.app"
  pos: 12
- name: "SourceTree"
  path: "/Applications/SourceTree.app"
  pos: 14
- name: "Xcode"
  path: "/Applications/Xcode.app"
  pos: 15
- name: "Paw"
  path: "/Applications/Paw.app"
  pos: 16
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

iterm2_fonts:
  - url: https://github.com/powerline/fonts/blob/master/Meslo%20Slashed/Meslo%20LG%20M%20Regular%20for%20Powerline.ttf?raw=true
iterm2_preferences_custom_folder: ~/Development/GitHub/iterm2-config
iterm2_shell_integration: yes

dotfiles_repo: https://github.com/matthijs2704/dotfiles.git
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .gitconfig
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc
  - .zshrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - doxygen
  - gettext
  - gifsicle
  - git
  - github/gh/gh
  - go
  - gpg
  - httpie
  - iperf
  - libevent
  - mcrypt
  - nmap
  - node
  - nvm
  - openssl
  - php
  - pinentry-mac
  - pure
  - pv
  - readline
  - sqlite
  - ssh-copy-id
  - wget
  - wrk
  - zsh-history-substring-search

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - discord
  - docker
  - firefox
  - gpg-suite-no-mail
  - handbrake 
  - home-assistant
  - iterm2
  - microsoft-edge
  - microsoft-office
  - microsoft-teams
  - parallels
  - paw
  - rectangle #todo config
  - sequel-ace
  - sourcetree
  - spotify
  - timing # Version 2018.3.2
  - vagrant
  - visual-studio-code
  - vlc
  - whatsapp

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - 424389933  # Final Cut Pro
  - 497799835  # Xcode
  - 1399498094 # WebSocket Client
  - 634159523  # MainStage
  - 634148309  # Logic Pro
  - 1037126344 # Apple Configurator 2
  - 425424353  # The Unarchiver
  - 434290957  # Motion
  - 1295203466 # Microsoft Remote Desktop
  - 1497506650 # Yubico Authenticator
  - 640199958  # Developer
  - 424390742  # Compressor
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure VSCode.
configure_vscode: true
vscode_settings: "files/vscode/settings.json"
vscode_installed_extensions:
  - amiralizadeh9480.laravel-extra-intellisense
  - apility.beautify-blade
  - christian-kohler.path-intellisense
  - codingyu.laravel-goto-view
  - CoenraadS.bracket-pair-colorizer-2
  - dbaeumer.vscode-eslint
  - Equinusocio.vsc-material-theme
  - equinusocio.vsc-material-theme-icons
  - esbenp.prettier-vscode
  - idleberg.applescript
  - James-Yu.latex-workshop
  - kevinglasson.cornflakes-linter
  - mikestead.dotenv
  - ms-azuretools.vscode-docker
  - ms-python.python
  - ms-python.vscode-pylance
  - ms-vscode-remote.remote-containers
  - ms-vscode.cpptools
  - ms-vsliveshare.vsliveshare
  - ms-vsliveshare.vsliveshare-audio
  - ms-vsliveshare.vsliveshare-pack
  - octref.vetur
  - onecentlin.laravel-blade
  - onecentlin.laravel-extension-pack
  - onecentlin.laravel5-snippets
  - platformio.platformio-ide
  - redhat.vscode-commons
  - redhat.vscode-yaml
  - rvest.vs-code-prettier-eslint
  - ryannaddy.laravel-artisan
  - sdras.vue-vscode-snippets
  - stef-k.laravel-goto-controller
  - stevemoser.xcode-keybindings
  - streetsidesoftware.code-spell-checker
  - Vtrois.gitmoji-vscode
  - yzhang.markdown-all-in-one
  - zbr.vscode-ansible

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
