---
- name: Ensure Visual Studio Code extensions are installed.
  command: code --install-extension {{ item | quote }}
  with_items: "{{ vscode_installed_extensions }}"
  register: vscode_install_extension_result
  changed_when: "'is already installed' not in vscode_install_extension_result.stdout"

- name: Ensure Visual Studio Code user settings and theme are set. 
  copy:
    src: "{{ vscode_settings }}"
    dest: "{{ ansible_env.HOME }}/Library/Application Support/Code/User/settings.json"
  when: vscode_settings is defined