---

- name: Ensure Dock icon size is set.
  community.general.osx_defaults: 
    domain: 'com.apple.dock'
    key: 'tilesize'
    type: int
    value: 50
  notify: Restart Dock

- name: Ensure Mission Control animation is sped up.
  community.general.osx_defaults: 
    domain: 'NSGlobalDomain'
    key: "expose-animation-duration"
    type: float
    value: 0.15
  notify: Restart Dock

- name: Ensure Dock icons of hidden applications are translucent.
  community.general.osx_defaults: 
    domain: 'com.apple.dock'
    key: showhidden
    type: bool
    value: true
  notify: Restart Dock

- name: Ensure Dock is auto-hiding.
  community.general.osx_defaults: 
    domain: 'com.apple.dock'
    key: autohide
    type: bool
    value: true
  notify: Restart Dock
