---

- name: Ensure screenshots are saved to Downloads.
  community.general.osx_defaults: 
    domain: 'com.apple.screencapture'
    key: location
    type: string
    value: "{{ ansible_env.HOME }}/Downloads"

- name: Ensure screenshots are saved as jpg.
  community.general.osx_defaults: 
    domain: 'com.apple.screencapture'
    key: type
    type: string
    value: jpg

- name: Ensure shadow in screenshots is disabled.
  community.general.osx_defaults: 
    domain: 'com.apple.screencapture'
    key: disable-shadow
    type: bool
    value: true