---

- name: Ensure TextEdit is plain and UTF-8.
  community.general.osx_defaults: { domain: 'com.apple.TextEdit', key: "{{ item.key }}", type: "{{ item.type }}", value: "{{ item.value }}" }
  loop:
    - {key: "RichText", type: int, value: 0 }
    - {key: "PlainTextEncoding", type: int, value: 4 }
    - {key: "PlainTextEncodingForWrite", type: int, value: 4 }