---
# - name: "See if Dock item {{ item.name | default(item) }} exists."
#   ansible.builtin.command: "dockutil --find '{{ item.name }}'"
#   register: dockitem_exists
#   failed_when: >
#     "No such file or directory" in dockitem_exists.stdout
#     or "command not found" in dockitem_exists.stdout
#   changed_when: false
#   tags: ['dock']

- name: Ensure Dock item {{ item.name | default(item) }} exists.
  ansible.builtin.command: "dockutil --add '{{ item.path }}' --replacing '{{ item.name | default(item) }}' --section apps --no-restart"
  # changed_when: dockitem_exists.rc > 0 or "in recent-apps" in dockitem_exists.stdout
  tags: ['dock']
  notify: Restart Dock